Traceback (most recent call last):
  File "./run.py", line 27, in <module>
slurmstepd: error: *** JOB 16895002 ON gr0580 CANCELLED AT 2020-03-20T11:32:51 DUE TO TIME LIMIT ***
